apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-backend
  labels:
    app: {{ .Chart.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "{{ .Values.backend.env.nodeEnv }}"
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: mongodb-uri
